### ISSUE TITLE
Add Java Version 16 to support upcoming releases

### ISSUE THREAD

**Issue by UNOPARATOR** [binhex/arch-minecraftserver#6]
I'm running a local papermc server and this warning started to show up lately:
> ************************************************************
> * WARNING - YOU ARE RUNNING AN OUTDATED VERSION OF JAVA.
> * PAPER WILL STOP BEING COMPATIBLE WITH THIS VERSION OF
> * JAVA WHEN MINECRAFT 1.17 IS RELEASED.
> *
> * Please update the version of Java you use to run Paper
> * to at least Java 16. When Paper for Minecraft 1.17 is
> * released support for versions of Java before 16 will
> * be dropped.
> *
> * Current Java version: 11.0.10
> *
> * Check this forum post for more information: 
> *   https://papermc.io/java16
> ************************************************************

If you would add Java version 16 to list of options, it would be great.

Which would also require changing the available environment variables from
> -e JAVA_VERSION=<8|11>

to
> -e JAVA_VERSION=<8|11|16>

amongst other things of course.

**Comment by binhex** [comment]
ok cool, i am awaiting an upstream version bump before this can happen, but it shouldn't be too much work, fyi here is the link:- https://archlinux.org/packages/extra/x86_64/jdk-openjdk/

**Comment by binhex** [comment]
added java 16, had to go with AUR package for now as AOR has not been updated, image is currently building.

**Comment by UNOPARATOR** [comment]
Thanks for the update, the new image is working fine with the JAVA_VERSION=16 settings.
