### ISSUE TITLE
[Feature Request] Toggle Download of Vanilla Minecraft

### ISSUE THREAD

**Issue by Unkn0wnCreator** [binhex/arch-minecraftserver#7]
hi,

i would love to see an toggle like true/false for turning off Downloading latest Vanilla version.

i use mostly Papermc and waterfall for bungeecord and i dont need the vanilla jar.

Like this its waste of space. When i run like 10 servers (game servers) and every server has like 40mb - 50mb wasted space it would use 400mb - 500mb of my harddrive for nothing

**Comment by binhex** [comment]
if you run 10 servers then due to shared docker layers you will use only 40MB not your suggested of 400-500.

**Comment by Unkn0wnCreator** [comment]
thats might be true but im using Unraid and save the Server files in one Share so in this case docker is not utilising this system.

**Comment by Unkn0wnCreator** [comment]
and a little not important thing

when running Bungeecord or else it wont boot until i added eula.txt and restart the container again.

**Comment by binhex** [comment]
ok ive taken a look at this and i have now put in a check, if the jar is custom (as defined by CUSTOM_JAR_PATH) then it will skip the file copy, i have also enhanced the generation of the eula to be generated next to the jar file, even for custom paths, please test this by specifying the 'test' tagged image.

**Comment by Unkn0wnCreator** [comment]
after testing with two servers (one Bungee, one papermc) i can say, it seems to be working verry well.

Thank you!

you can close this issue if there are no more questions

**Comment by binhex** [comment]
> after testing with two servers (one Bungee, one papermc) i can say, it seems to be working verry well.
> 
> Thank you!
> 
> you can close this issue if there are no more questions

excellent! thanks for letting me know, i will tag this as 'latest' shortly, so please switch back in an hour from now.
